import type { Metadata } from "next";
import { Outfit } from "next/font/google";
import "../globals.css";
import { Toaster } from "sonner";

const outfit = Outfit({
  subsets: ["latin"],
  display: "swap",
  weight: "400",
  variable: "--font-outfit",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${outfit.className} bg-primary flex items-center justify-center min-h-screen antialiased`}
      >
        <div className="max-w-160 w-full min-h-160 my-4 bg-white border border-sky mx-3 rounded-xl sm:rounded-[30px] px-2.5">
          <div className="flex items-center mx-auto max-w-130 justify-center py-8 flex-col">
            <main className=" w-full "> {children}</main>{" "}
            <Toaster position="top-center" />
          </div>
        </div>
      </body>
    </html>
  );
}
