import type { Metadata } from "next";
import { Outfit } from "next/font/google";
import "../globals.css";
import Tabs from "@/components/tab/Tabs";

const outfit = Outfit({
  subsets: ["latin"],
  display: "swap",
  weight: "400",
  variable: "--font-outfit",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${outfit.className} bg-primary flex items-center justify-center min-h-screen antialiased`}
      >
        <div className="max-w-160 w-full h-[762px] bg-white border border-sky rounded-[30px]">
          <div className="flex items-center mx-auto max-w-130 justify-center py-8 flex-col">
            <Tabs />
            <main className="mt-8"> {children}</main>
          </div>
        </div>
      </body>
    </html>
  );
}
