import type { Metadata } from "next";
import { Outfit } from "next/font/google";
import "../globals.css";
import Tabs from "@/components/tab/Tabs";
import { Toaster } from "@/components/ui/sonner";

import Presence from "@/components/Presence";
const outfit = Outfit({
  subsets: ["latin"],
  display: "swap",
  weight: "400",
  variable: "--font-outfit",
});

export const metadata: Metadata = {
  title: "Novacrust",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${outfit.className} bg-primary flex items-center justify-center min-h-screen antialiased`}
      >
        <div className="max-w-160 w-full my-4 min-h-160 bg-white border border-sky rounded-xl mx-3 sm:rounded-[30px] px-2.5">
          <div className="flex items-center mx-auto max-w-130 justify-center py-8 flex-col">
            <Tabs />
            <Presence>{children}</Presence>
            <Toaster position="top-center" />
          </div>
        </div>
      </body>
    </html>
  );
}
